### ISSUE TITLE
Idea, for this mod or for a new one.

### ISSUE THREAD

**Issue by K0-RR** [TeamMidnightDust/ThisRocks#10]
I know it's something different from what this mod adds currently but somehow in my mind this fits nice together. Puddles, [like in this outdated forge mod](https://www.curseforge.com/minecraft/mc-mods/puddles). They would appear on solid blocks when it rains. You would be able to fill a glass bottle (this would play nicely with the Dehydration mod) from them and then a puddle would disappear. After rain and a few seconds/minutes they would vanish.

![image](https://user-images.githubusercontent.com/43277609/102785127-be813f80-439d-11eb-84cc-c9c8a06d79be.png)

**Comment by Motschen** [comment]
I really enjoyed this mod in the 1.12 days. Maybe I'll create this as a separate mod.
I'm gonna close this now, since it isn't really related to This Rocks.
