### ISSUE TITLE
Place Rocks (feature request)

### ISSUE THREAD

**Issue by mccormack-harry** [TeamMidnightDust/ThisRocks#12]
Players should be able to place down splitters to create rocks, I like that rocks are generated but I also want to scatter some around for decoration.
When one is placed it should be given a random model (can be broken and replaced for another random).
I like that you can only cycle them in creative.
Also players should be able to craft splitters, e.g. 1 cobblestone -> 4 splitters. 1 netherack -> 4 netherack splitters.

**Comment by K0-RR** [comment]
+1
