### ISSUE TITLE
Feature Req: Generate Crimson and Warped sticks in their respective biomes in the Nether

### ISSUE THREAD

**Issue by sableseyler** [TeamMidnightDust/ThisRocks#17]
I would really appreciate it if you could add sticks for the warped and crimson fungus trees, making it possible to use "no tree punching"-esque mods like EarlyGame with a Nether start, or in situations where you've lost your tools and need to rebuild while still in the Nether.

**Comment by Motschen** [comment]
Added in 1.5.0 :)
