### ISSUE TITLE
Starfish WTHIT incompatibility

### ISSUE THREAD

**Issue by Muffintiem** [TeamMidnightDust/ThisRocks#23]
Whenever I try looking directly at a starfish with WTHIT it makes the game crash. If I remove WTHIT it doesn't crash anymore. I'm playing in the 1.17.1 version.

**Comment by DoctorArchives** [comment]
Same for me.

**Comment by neonailol** [comment]
Having the same problem, crash log attached
[crash-2021-09-22_08.03.19-client.txt](https://github.com/TeamMidnightDust/ThisRocks/files/7207874/crash-2021-09-22_08.03.19-client.txt)

**Comment by milkev** [comment]
can confirm still happens with wthit v3.9.3

**Comment by Motschen** [comment]
This also applied when picking the starfish in Creative mode.
It's been fixed in the latest release, sorry for the long wait, and thanks for reporting everyone <3!
