### ISSUE TITLE
Game Crashing.

### ISSUE THREAD

**Issue by RougeJr** [TeamMidnightDust/ThisRocks#44]
Hi, Im usinng Fabric on minecraft 1.20.6 and the game crashes.
[crash-2024-06-17_05.26.10-client.txt](https://github.com/user-attachments/files/15864082/crash-2024-06-17_05.26.10-client.txt)

**Comment by Motschen** [comment]
1.20.6 is not supported. Please use 1.21 or 1.20.1.
