### ISSUE TITLE
Another random crash with Sodium

### ISSUE THREAD

**Issue by K0-RR** [TeamMidnightDust/ThisRocks#9]
---- Minecraft Crash Report ----
// My bad.

Time: 2020-12-19 11:29:14 CET
Description: Rendering Block Entity

java.lang.IllegalArgumentException: Cannot get property class_2754{name=variation, clazz=class eu.midnightdust.motschen.rocks.blockstates.StarfishVariation, values=[red, pink, orange]} as it does not exist in Block{minecraft:air}
    at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.7)
    at net.minecraft.state.State.get(State:95)
    at eu.midnightdust.motschen.rocks.block.blockentity.StarfishBlockEntity.getVariation(StarfishBlockEntity.java:14)
    at eu.midnightdust.motschen.rocks.block.render.StarfishBlockEntityRenderer.render(StarfishBlockEntityRenderer.java:78)
    at eu.midnightdust.motschen.rocks.block.render.StarfishBlockEntityRenderer.render(StarfishBlockEntityRenderer.java:17)
    at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.render(BlockEntityRenderDispatcher:107)
    at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.method_23081(BlockEntityRenderDispatcher:96)
    at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.runReported(BlockEntityRenderDispatcher:128)
    at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.render(BlockEntityRenderDispatcher:96)
    at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:302)
    at net.minecraft.client.render.WorldRenderer.handler$zzc000$onRenderTileEntities(WorldRenderer:3716)
    at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1265)
    at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:727)
    at net.minecraft.client.render.GameRenderer.render(GameRenderer:546)
    at net.minecraft.client.MinecraftClient.render(MinecraftClient:1048)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:681)
    at net.minecraft.client.main.Main.main(Main:215)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:564)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:564)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Block Entity Details --
  Name: rocks:starfish_blockentity // eu.midnightdust.motschen.rocks.block.blockentity.StarfishBlockEntity
  Block: Block{rocks:starfish}[waterlogged=false,variation=red]
  Block location: World: (109,66,-184), Chunk: (at 13,4,8 in 6,-12; contains blocks 96,0,-192 to 111,255,-177), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
  Block: Block{minecraft:air}
  Block location: World: (109,66,-184), Chunk: (at 13,4,8 in 6,-12; contains blocks 96,0,-192 to 111,255,-177), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
  Block Entity NBT: {z:-184,id:"rocks:starfish_blockentity",x:109,y:66}

-- Affected level --
  All players: 1 total; [class_746['_K0RR_'/205, l='ClientLevel', x=111.96, y=62.31, z=-192.62]]
  Chunk stats: SodiumChunkCache: 576
  Level dimension: minecraft:overworld
  Level spawn location: World: (160,65,-208), Chunk: (at 0,4,0 in 10,-13; contains blocks 160,0,-208 to 175,255,-193), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
  Level time: 24264 game time, 1351535 day time
  Server brand: fabric
  Server type: Integrated singleplayer server

-- System Details --
  Minecraft Version: 1.16.4
  Minecraft Version ID: 1.16.4
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 15, AdoptOpenJDK
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), AdoptOpenJDK
  Memory: 1197247968 bytes (1141 MB) / 3221225472 bytes (3072 MB) up to 3221225472 bytes (3072 MB)
  CPUs: 4
  JVM Flags: 9 total; -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms3072m -Xmx3072m
  Suspected Mods: This Rocks! (rocks), Fabric Loader (fabricloader), Sodium (sodium)
  Fabric Mods: adorn: Adorn 1.12.2+1.16.4
               advdebug: Advancements Debug 2.2.0
               allure: Allure 1.2.8
               angerable-patch: Angerable Patch 1.0.0-1.16.1
               appleskin: AppleSkin 1.0.11
               astromine: Astromine 1.12.0+fabric-1.16.4
               astromine-core: Astromine: Core 1.12.0+fabric-1.16.4
               astromine-discoveries: Astromine: Discoveries 1.12.0+fabric-1.16.4
               astromine-foundations: Astromine: Foundations 1.12.0+fabric-1.16.4
               astromine-technologies: Astromine: Technologies 1.12.0+fabric-1.16.4
               astromine-transportations: Astromine: Transportations 1.12.0+fabric-1.16.4
               autoconfig1u: Auto Config v1 Updated 3.3.1
               autoswitch: AutoSwitch 2.11.6
               autoswitch-api: AutoSwitch API 1.0.0
               battletowers: Battle Towers 3.3.1-beta-1.16.4
               beebetter: Bee Better 1.8.0-1.16.4
               bendy-lib: Bendy api 0.2.3
               bettercaves: YUNG's Better Caves 1.16.2-1.0.3
               bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0
               betterstones: Better Stones 0.0.4
               biomemakeover: Biome Makeover 1.16.4-1.1.5
               blade: Blade 2.0.0
               blame: Blame 2.2.4
               blockus: Blockus 1.6.8+1.16.4
               byg: BYG 1.1.3
               campanion: Campanion 1.3.0+build.49
               cardinal-components-base: Cardinal Components API (base) 2.7.9
               cardinal-components-block: Cardinal Components API (blocks) 2.7.9
               cardinal-components-chunk: Cardinal Components API (chunks) 2.7.8
               cardinal-components-entity: Cardinal Components API (entities) 2.7.9
               cardinal-components-item: Cardinal Components API (items) 2.7.9
               cardinal-components-level: Cardinal Components API (world saves) 2.7.8
               cardinal-components-util: Cardinal Components API (utilities) 2.7.8
               cardinal-components-world: Cardinal Components API (worlds) 2.7.8
               cavebiomes: Cave Biomes 0.5.1
               charm: Charm 2.1.4
               chat_heads: Chat Heads 0.2.1+1.16.2
               chesttracker: Chest Tracker 0.7.9
               chunkpregen: Fabric Chunk Pregenerator 0.3.3
               cinderscapes: Cinderscapes 1.3.0+build.51
               climbable: Climbable 0.2.0
               cloth-basic-math: Cloth Basic Math 0.5.1
               cloth-client-events-v0: Cloth Client Events v0 1.4.8
               cloth-common-events-v1: Cloth Common Events v1 1.4.9
               cloth-config2: Cloth Config v4 4.8.3
               cloth-datagen-api-v1: Cloth Datagen v1 1.4.9
               cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.9
               cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.9
               com_electronwill_night-config_core: core 3.6.2
               com_electronwill_night-config_toml: toml 3.6.2
               com_moandjiezana_toml_toml4j: toml4j 0.7.2
               cotton-config: Cotton Config 1.0.0-rc.7
               cotton-logging: Cotton Logging 1.0.0-rc.4
               crimsonmoon: Crimson Moon 1.2.3-1.16.2
               croptopia: Croptopia 1.0.5-1.16.3-FABRIC
               crumbs: Crumbs 1.0.2+1.16.4-fabric
               cullleaves: Cull Leaves 1.0.0
               curios: Curios API 0.0.10-1.16.3
               customportals: Custom Portals 1.3.0
               dawn: Dawn API 1.6
               dehydration: Dehydration 1.0.8
               dungeons_of_exile: Dungeons of Exile 1.1.1
               dynamicsoundfilters: Dynamic Sound Filters 1.1.3+1.16.2
               dynocaps: DynoCaps 1.6.10
               emerald_tools: Emerald Tools 1.0.43
               emotecraft: Emotecraft 1.2.3
               environmentz: EnvironmentZ 1.0.7
               expandedconcrete: Expanded Concrete 0.0.2
               fabriblocks: FabriBlocks 1.2.1
               fabric: Fabric API 0.28.0+1.16
               fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
               fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+6a2618f53a
               fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
               fabric-commands-v0: Fabric Commands (v0) 0.2.0+6a2618f53a
               fabric-containers-v0: Fabric Containers (v0) 0.1.9+a03e98793a
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
               fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+6a2618f53a
               fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
               fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+6a2618f53a
               fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+6a2618f53a
               fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
               fabric-language-scala: Fabric Language Scala 0.3.2.12
               fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+ffb68a873a
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+6a2618f53a
               fabric-models-v0: Fabric Models (v0) 0.1.1+6a2618f53a
               fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+4358fbc63a
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.7+a03e98793a
               fabric-networking-v0: Fabric Networking (v0) 0.3.0+a03e98793a
               fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
               fabric-particles-v1: fabric-particles-v1 0.2.2+6a2618f53a
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.2+a03e98793a
               fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+6a2618f53a
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+6a2618f53a
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+6a2618f53a
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+6a2618f53a
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+6a2618f53a
               fabric-rendering-v1: Fabric Rendering (v1) 1.4.0+6a2618f53a
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.2+1944f3e03a
               fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
               fabric-structure-api-v1: Fabric Structure API (v1) 1.1.1+f1d8af063a
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
               fabric-textures-v0: Fabric Textures (v0) 1.0.5+6a2618f53a
               fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
               fabrication: Fabrication 1.2.3_02
               fabricloader: Fabric Loader 0.10.8
               fairenchanting: FairEnchanting 1.2.0
               fallflyinglib: FallFlyingLib 1.1.0
               fermion: Fermion 2.1.191
               fermion-modkeys: Fermion Modifier Keys 1.8.180-snapshot
               fiber: fiber 0.23.0-2
               flight_rings: Flight Rings 1.4.2
               flyring: Ring of Flight 0.1.0+1.16.4
               grindenchantments: Grind Enchantments 1.1.3+1.16.3
               hydrogen: Hydrogen 0.1.1
               images: Images 0.4.0+1.16.4
               inventorytabs: Inventory Tabs 0.2.3-1.16.4
               jankson: Jankson 3.0.1+j1.2.0
               jumplessstep: Jumpless Step 0.1.0+1.16.1
               lambdynlights: LambDynamicLights 1.3.2+1.16.4
               lapisreserve: Lapis Reserve 1.0.6
               libblockattributes_core: LibBlockAttributes (Core) 0.8.4
               libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.4
               libblockattributes_items: LibBlockAttributes (Items) 0.8.4
               libcd: LibCapableData 3.0.3+1.16.3
               libgui: LibGui 3.2.1+1.16.3
               library_of_exile: Library of Exile 1.0.6
               libstructure: LibStructure 1.5
               lightstones: Lightstones 1.2
               lithium: Lithium 0.6.0
               lithium-api: Lithium API 0.6.0
               loadcatcher: Entrypoint Catcher 2.0.0
               magna: Magna 1.4.3-1.16.2
               malilib: MaLiLib 0.10.0-dev.21+arne.2
               mambience: MAmbience 2.1.0+1.16.2
               midnight-hats: Midnight Hats 2.0.1
               minecraft: Minecraft 1.16.4
               minegate-moreblocks: MineGate - MoreBlocks 1.0.1
               minimaltweaks: Minimal Tweaks 1.0.3
               mixedslab: Mixed Slab 1.16.3-1.2
               modmenu: Mod Menu 1.14.13+build.19
               more_gems: More Gems 1.1.12
               moreblocksmod: More Blocks Mod 1.0.0
               morecraftingtables: Oh, How the Crafting Has Tabled! 0.1.3-1.16.3
               mythicmetals: Mythic Metals 0.9.7
               nbtcrafting: NBT Crafting 2.0.0-rc.7+mc1.16.2-pre1
               nookbuild: NookBuild 1.2.1
               notenoughcrashes: Not Enough Crashes 2.1.4+1.16.4
               nourish: Nourish 1.1.1
               okzoomer: Ok Zoomer 4.0.1+1.16.2
               org_aeonbits_owner_owner: owner 1.0.10
               org_jetbrains_annotations: annotations 20.0.0
               org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
               org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
               org_joml_joml: joml 1.9.25
               origins: Origins 0.4.5
               patchouli: Patchouli 1.16.4-48-FABRIC
               phosphor: Phosphor 0.7.0+build.10
               piglib: Piglib 1.0.1
               playerabilitylib: Pal 1.2.1
               polymorph: Polymorph 0.0.6-1.16.4
               rare-ice: Rare Ice 0.2.2
               reach-entity-attributes: Reach Entity Attribute 1.0.2
               reroll: Reroll 1.0.2-1.16.2
               ringsofascension: Rings of Ascension 1.1.1
               riverredux: River Redux 0.1.5
               rocks: This Rocks! 1.2.2
               roughlyenoughitems: Roughly Enough Items 5.8.10
               roughlyenoughitems-api: REI (API) 5.8.10
               roughlyenoughitems-default-plugin: REI (Default Plugin) 5.8.10
               roughlyenoughitems-runtime: REI (Runtime) 5.8.10
               rpgstats: RPGStats 2.3.2+1.16.3
               satin: Satin 1.4.1
               seasons: Fabric Seasons 1.0.3-BETA
               shapes: Shapes 2.0.0+build.10
               simpleteleporters: Simple Teleporters 2.2.1
               slyde: Slyde 1.1
               snowdrift: Snowdrift ${version}
               snowy_leaves: Snowy Leaves 1.16.1-1.3.1
               sodium: Sodium 0.1.0
               spiceoffabric: Spice of Fabric 1.2.6+1.16.3
               spruceui: SpruceUI 1.6.4
               static-content: Static Content 1.0.1-1.16.2
               staticdata: Static Data 1.1.2
               structure-helpers: Structure Helpers 3.0.0
               team_reborn_energy: Energy 0.1.1
               terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.0+build.1
               terraform-config-api-v1: Terraform Config API (v1) 1.0.0+build.1
               terraform-dirt-api-v1: Terraform Dirt API (v1) 1.0.0+build.1
               terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.0+build.1
               terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.0+build.3
               terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.0+build.1
               terraform-tree-api-v1: Terraform Tree API (v1) 1.0.1+build.3
               terraform-wood-api-v1: Terraform Wood API (v1) 1.0.0+build.1
               terrestria: Terrestria 2.1.5+build.28
               texp: Terran Expansion 1.1.1
               tiered: Tiered 1.2.0-beta-1.16.4
               tinytweaks: TinyTweaks 1.1.2
               tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
               traverse: Traverse 3.0.3+build.13
               trinkets: Trinkets 2.6.7
               tweed: Tweed API 3.0.0-beta.15
               unearthed: Unearthed 1.0.5
               upstream: Upstream 1.0.1
               vanilla-toolsets: Vanilla Toolsets 1.3.0
               vanillaenhanced: VanillaEnhanced 1.3.1
               waystones: Waystones 1.0.10
               wild_explorer: Wild Explorer 1.3
               wildworld: Wild World 1.3.0+1.16.2
               wolveswitharmor: Wolves With Armor 1.5.2-1.16.2
               woods_and_mires: Woods and Mires 1.0.4+1.16.3
               woodsplus: Woods Plus 0.0.2
               wrenchable: Wrenchable 1.0.0+1.16.1
               xpstorage: XP Storage 1.2+1.16.4
               yungsapi: YUNG's API 1.16.4-Fabric-1
  Patchouli open book context: n/a
  Launched Version: MultiMC5
  Backend library: LWJGL version 3.2.2 build 10
  Backend API: AMD Radeon(TM) Vega 3 Graphics GL version 4.6.13559 Compatibility Profile Context 26.20.12036.1, ATI Technologies Inc.
  GL Caps: Using framebuffer using OpenGL 3.0
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fabric'
  Type: Client (map_client.txt)
  Graphics mode: fancy
  Resource Packs: fabric/fallflyinglib, fabric/fermion, fabric/dynamicsoundfilters, fabric/snowy_leaves, fabric/fabricloader, fabric/trinkets, fabric/riverredux, fabric/fabric-game-rule-api-v1, fabric/fermion-modkeys, fabric/fabric-api-base, fabric/dehydration, fabric/astromine-discoveries, fabric/snowdrift, fabric/terraform-dirt-api-v1, fabric/playerabilitylib, fabric/astromine-transportations, fabric/dynocaps, fabric/astromine-foundations, fabric/terraform-wood-api-v1, fabric/chat_heads, fabric/morecraftingtables, fabric/dawn, fabric/fabric-networking-v0, fabric/modmenu, fabric/phosphor, fabric/roughlyenoughitems-runtime, fabric/battletowers, fabric/midnight-hats, fabric/autoswitch, fabric/structure-helpers, fabric/fabric-crash-report-info-v1, fabric/curios, fabric/origins, fabric/nbtcrafting, fabric/fabric-key-binding-api-v1, fabric/staticdata, fabric/magna, fabric/libblockattributes_fluids, fabric/adorn, fabric/vanillaenhanced, fabric/fabric-networking-api-v1, fabric/bettermineshafts, fabric/terraform-shapes-api-v1, fabric/terrestria, fabric/mambience, fabric/grindenchantments, fabric/expandedconcrete, fabric/fairenchanting, fabric/lithium, fabric/fabric-object-builder-api-v1, fabric/ringsofascension, fabric/terraform-config-api-v1, fabric/tinytweaks, fabric/fabric-rendering-data-attachment-v1, fabric/seasons, fabric/terraform-surfaces-api-v1, fabric/wolveswitharmor, fabric/fabric-lifecycle-events-v1, fabric/sodium, fabric/fabric-loot-tables-v1, fabric/crumbs, fabric/moreblocksmod, fabric/blame, fabric/libblockattributes_core, fabric/emotecraft, fabric/terraform-biome-builder-api-v1, fabric/xpstorage, fabric/jankson, fabric/woods_and_mires, fabric/fabric-command-api-v1, fabric/advdebug, fabric/fabric-renderer-indigo, fabric/mixedslab, fabric/emerald_tools, fabric/shapes, fabric/libgui, fabric/vanilla-toolsets, fabric/fabric-rendering-v0, fabric/croptopia, fabric/fabric-rendering-v1, fabric/polymorph, fabric/autoconfig1u, fabric/fabric-tag-extensions-v0, fabric/byg, fabric/cinderscapes, fabric/fabric-events-lifecycle-v0, fabric/flight_rings, fabric/climbable, fabric/customportals, fabric/team_reborn_energy, fabric/mythicmetals, fabric/fabric-keybindings-v0, fabric/notenoughcrashes, fabric/satin, fabric/rpgstats, fabric/texp, fabric/nookbuild, fabric/images, fabric/lambdynlights, fabric/fabrication, fabric/betterstones, fabric/beebetter, fabric/fabric-blockrenderlayer-v1, fabric/libblockattributes_items, fabric/fabric, fabric/wrenchable, fabric/autoswitch-api, fabric/fabric-screen-handler-api-v1, fabric/wild_explorer, fabric/fabric-tool-attribute-api-v1, fabric/terraform-tree-api-v1, fabric/crimsonmoon, fabric/unearthed, fabric/blockus, fabric/fabric-events-interaction-v0, fabric/fabric-language-kotlin, fabric/cullleaves, fabric/cloth-config2, fabric/nourish, fabric/fabric-resource-loader-v0, fabric/astromine-technologies, fabric/fabric-registry-sync-v0, fabric/fabric-mining-levels-v0, fabric/woodsplus, fabric/fabric-item-groups-v0, fabric/fabric-models-v0, fabric/reroll, fabric/lightstones, fabric/fabric-renderer-api-v1, fabric/environmentz, fabric/libcd, fabric/biomemakeover, fabric/cavebiomes, fabric/allure, fabric/simpleteleporters, fabric/blade, fabric/fabric-containers-v0, fabric/waystones, fabric/campanion, fabric/fabric-textures-v0, fabric/minimaltweaks, fabric/fabric-rendering-fluids-v1, fabric/chesttracker, fabric/traverse, fabric/fabric-renderer-registries-v1, fabric/wildworld, fabric/more_gems, fabric/fabric-networking-blockentity-v0, fabric/okzoomer, fabric/bendy-lib, fabric/flyring, fabric/roughlyenoughitems, fabric/rocks, fabric/fabric-item-api-v1, fabric/terraform-overworld-biome-extensions-api-v1, fabric/spruceui, fabric/fabric-content-registries-v0, fabric/tiered, fabric/fabric-biome-api-v1, fabric/spiceoffabric, fabric/jumplessstep, fabric/inventorytabs, fabric/astromine-core, fabric/fabric-object-builders-v0
  Current Language: English (US)
  CPU: 4x AMD Ryzen 3 2200U with Radeon Vega Mobile Gfx
  Client Crashes Since Restart: 1
  Integrated Server Crashes Since Restart: 0

**Comment by Motschen** [comment]
Could you try if it also happens with This Rocks 1.2.1

**Comment by K0-RR** [comment]
I will do my best but it's hard because I don't know how to manually cause this crash, so far they was too random.
